//! The "Differential fidelity corpus" section of `docs/sql-coverage.md`.
//!
//! The document is the shim registry's coverage table (rendered by
//! `glaux_athena::dialect::registry::render_coverage`) followed by this
//! section, which is generated from an actual replay: every corpus case,
//! the formats it touches, whether glaux matched its snapshot, and whether
//! that snapshot was verified against real Athena or is still
//! self-recorded.

use glaux_athena::dialect::registry::render_coverage;

use crate::firehose::ArtifactReport;
use crate::snapshot::Provenance;
use crate::suite::{CaseReport, CaseResult};

/// Marker the section starts with; the registry part of the document ends
/// right before it.
pub const SECTION_MARKER: &str = "<!-- GENERATED by glaux-fidelity (crates/glaux-fidelity) from a replay of the corpus.\n     Do not edit by hand: run `cargo run -p glaux-fidelity -- coverage`. -->";

/// The full document: registry coverage + fidelity section.
pub fn render_document(reports: &[CaseReport], firehose: &[ArtifactReport]) -> String {
    format!(
        "{}\n{}",
        render_coverage(),
        render_section(reports, firehose)
    )
}

fn provenance_cell(p: Option<&Provenance>) -> String {
    match p {
        None => "**missing**".to_string(),
        Some(Provenance::Athena {
            region,
            engine,
            recorded,
        }) => format!("verified ({engine}, {region}, {recorded})"),
        Some(Provenance::Unverified { recorded }) => {
            format!("UNVERIFIED (glaux self-recorded {recorded})")
        }
    }
}

fn result_cell(result: &CaseResult) -> String {
    match result {
        CaseResult::Match => "match".to_string(),
        CaseResult::MissingSnapshot => "**no snapshot**".to_string(),
        CaseResult::Mismatch(d) => format!("**MISMATCH** ({} difference(s))", d.len()),
    }
}

/// Render the section alone.
pub fn render_section(reports: &[CaseReport], firehose: &[ArtifactReport]) -> String {
    let mut out = String::new();
    out.push_str(SECTION_MARKER);
    out.push_str("\n## Differential fidelity corpus\n\n");
    let total = reports.len();
    let verified = reports
        .iter()
        .filter(|r| r.provenance.as_ref().is_some_and(Provenance::is_verified))
        .count();
    let unverified = reports
        .iter()
        .filter(|r| r.provenance.as_ref().is_some_and(|p| !p.is_verified()))
        .count();
    let matched = reports.iter().filter(|r| r.passed()).count();
    let positive = reports.iter().filter(|r| !r.case.is_negative()).count();
    out.push_str(&format!(
        "Every corpus query runs against glaux's Athena service over the fixture tables stored as \
         Parquet (`customers`), NDJSON (`orders`) and delimited text (`countries`), and is diffed \
         against a recorded snapshot (`crates/glaux-fidelity/tests/snapshots/`). Rows are compared \
         positionally under a top-level `ORDER BY` and as a multiset otherwise; floating-point \
         columns within a relative 1e-9; timestamps as instants. Negative cases must fail naming \
         the construct the corpus expects.\n\n\
         **{total} cases** ({positive} queries, {} error cases): {matched} match their snapshot. \
         Snapshot provenance: **{verified} verified against real Athena**, {unverified} UNVERIFIED \
         (self-recorded from glaux; re-record with `cargo run -p glaux-fidelity -- record`).\n\n",
        total - positive
    ));
    if unverified > 0 {
        out.push_str(
            "> **UNVERIFIED** snapshots pin glaux's current behaviour so regressions are caught, but \
             they do not yet prove agreement with AWS Athena. Treat the `match` column for those rows \
             as \"stable\", not \"verified\".\n\n",
        );
    }
    out.push_str("| Case | Kind | Tables (format) | Result | Snapshot |\n|---|---|---|---|---|\n");
    for r in reports {
        let kind = match &r.case.expect_error {
            Some(needle) => format!("error case (`{needle}`)"),
            None => format!("query, {}", r.case.compare.as_str()),
        };
        let tables = if r.case.tables.is_empty() {
            "—".to_string()
        } else {
            r.case
                .tables
                .iter()
                .map(|t| {
                    let format = crate::fixtures::table(t)
                        .map(|f| f.format.label())
                        .unwrap_or("?");
                    format!("{t} ({format})")
                })
                .collect::<Vec<_>>()
                .join(", ")
        };
        out.push_str(&format!(
            "| {} | {kind} | {tables} | {} | {} |\n",
            r.case.name,
            result_cell(&r.result),
            provenance_cell(r.provenance.as_ref())
        ));
    }
    out.push_str("\n### Firehose delivery artifacts\n\n");
    out.push_str(
        "Object keys are checked against Firehose's naming contract (prefix resolved at the flush \
         instant, `<stream>-<version>-<yyyy-MM-dd-HH-mm-ss>-<uuid>[.ext]`) and snapshotted in \
         template form; object contents are decoded (gunzipped, Parquet → Athena text) and pinned \
         line by line.\n\n| Scenario | Objects | Result | Snapshot |\n|---|---|---|---|\n",
    );
    for r in firehose {
        let objects = match &r.actual {
            crate::snapshot::Outcome::Succeeded { rows, .. } => {
                let mut keys: Vec<&str> = rows.iter().filter_map(|row| row[0].as_deref()).collect();
                keys.dedup();
                keys.iter()
                    .map(|k| format!("`{k}`"))
                    .collect::<Vec<_>>()
                    .join("<br>")
            }
            crate::snapshot::Outcome::Failed { message } => format!("failed: {message}"),
        };
        out.push_str(&format!(
            "| {} | {objects} | {} | {} |\n",
            r.name,
            result_cell(&r.result),
            provenance_cell(r.provenance.as_ref())
        ));
    }
    out
}
