//! Outcomes, snapshots, normalization and diffing.
//!
//! A snapshot is one small text file per case:
//!
//! ```text
//! # glaux fidelity snapshot — generated by glaux-fidelity; do not edit by hand
//! # case: shape_join_left_using
//! # provenance: athena region=eu-central-1 engine="Athena engine version 3" recorded=2026-08-21
//! # compare: ordered
//! status: SUCCEEDED
//! columns: [["id","bigint"],["name","varchar"]]
//! row: ["1","Alice"]
//! row: ["5",null]
//! ```
//!
//! or, for a negative case, `status: FAILED` followed by `error: "<json>"`.
//! Cells are JSON-encoded so delimiters, newlines and NULL survive verbatim.
//!
//! # Normalization
//!
//! Comparison ([`diff`]) is textual except where Athena and glaux legitimately
//! differ in representation but not in value:
//!
//! - **row order** — positional only when the case is [`Compare::Ordered`];
//!   otherwise both sides are sorted by a normalized key first;
//! - **floating point** (`double`, `real`, `float`) — numeric comparison
//!   with relative tolerance [`FLOAT_RELATIVE_TOLERANCE`]; `NaN`, `Infinity`
//!   and `-Infinity` must match exactly;
//! - **timestamps** — parsed and compared as instants, so `.000` vs
//!   `.000000` or a missing fraction never count as a difference.
//!
//! Column names and Athena types are compared exactly. The tolerances are
//! deliberately tight: the suite exists to find differences, not to paper
//! over them.

use std::fmt;
use std::fs;
use std::path::Path;

use chrono::NaiveDateTime;
use serde_json::Value;

use crate::corpus::Compare;
use crate::{HarnessError, Result};

/// Relative tolerance for floating-point columns.
pub const FLOAT_RELATIVE_TOLERANCE: f64 = 1e-9;

/// A result column: Athena name and type text (e.g. `decimal(10,2)`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Column {
    /// Column label.
    pub name: String,
    /// Athena type, with precision/scale for decimals.
    pub type_name: String,
}

impl Column {
    /// Whether values compare numerically with tolerance.
    pub fn is_floating(&self) -> bool {
        matches!(self.type_name.as_str(), "double" | "real" | "float")
    }

    /// Whether values compare as instants.
    pub fn is_timestamp(&self) -> bool {
        self.type_name.starts_with("timestamp")
    }
}

/// What running one case produced, on either side.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Outcome {
    /// The query succeeded.
    Succeeded {
        /// Result columns.
        columns: Vec<Column>,
        /// Data rows (no header); `None` is NULL.
        rows: Vec<Vec<Option<String>>>,
    },
    /// The query failed with this message.
    Failed {
        /// The engine's error text.
        message: String,
    },
}

impl Outcome {
    /// `SUCCEEDED` / `FAILED`.
    pub fn status(&self) -> &'static str {
        match self {
            Outcome::Succeeded { .. } => "SUCCEEDED",
            Outcome::Failed { .. } => "FAILED",
        }
    }
}

/// Where a snapshot's expected values came from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Provenance {
    /// Recorded against real AWS Athena.
    Athena {
        /// AWS region of the scratch resources.
        region: String,
        /// `EffectiveEngineVersion` Athena reported.
        engine: String,
        /// Recording date (`YYYY-MM-DD`).
        recorded: String,
    },
    /// Recorded from glaux itself: NOT verified against AWS.
    Unverified {
        /// Recording date (`YYYY-MM-DD`).
        recorded: String,
    },
}

impl Provenance {
    /// `true` for snapshots recorded against real Athena.
    pub fn is_verified(&self) -> bool {
        matches!(self, Provenance::Athena { .. })
    }

    fn render(&self) -> String {
        match self {
            Provenance::Athena {
                region,
                engine,
                recorded,
            } => format!(
                "athena region={} engine={} recorded={recorded}",
                Value::String(region.clone()),
                Value::String(engine.clone()),
            ),
            Provenance::Unverified { recorded } => format!(
                "UNVERIFIED recorded={recorded} — recorded from glaux itself because no AWS \
                 profile was available; re-record with `cargo run -p glaux-fidelity -- record`"
            ),
        }
    }

    fn parse(text: &str) -> Result<Self> {
        if let Some(rest) = text.strip_prefix("UNVERIFIED ") {
            let recorded = rest
                .strip_prefix("recorded=")
                .and_then(|s| s.split_whitespace().next())
                .ok_or_else(|| HarnessError::new(format!("bad provenance {text:?}")))?;
            return Ok(Provenance::Unverified {
                recorded: recorded.to_string(),
            });
        }
        let rest = text
            .strip_prefix("athena ")
            .ok_or_else(|| HarnessError::new(format!("bad provenance {text:?}")))?;
        // region="..." engine="..." recorded=YYYY-MM-DD — values are JSON strings.
        let (region, rest) = take_json_field(rest, "region")?;
        let (engine, rest) = take_json_field(rest.trim_start(), "engine")?;
        let recorded = rest
            .trim_start()
            .strip_prefix("recorded=")
            .ok_or_else(|| HarnessError::new(format!("bad provenance {text:?}")))?;
        Ok(Provenance::Athena {
            region,
            engine,
            recorded: recorded.trim().to_string(),
        })
    }
}

fn take_json_field<'a>(text: &'a str, key: &str) -> Result<(String, &'a str)> {
    let rest = text
        .strip_prefix(key)
        .and_then(|s| s.strip_prefix('='))
        .ok_or_else(|| HarnessError::new(format!("expected {key}= in {text:?}")))?;
    let mut de = serde_json::Deserializer::from_str(rest).into_iter::<String>();
    let value = de
        .next()
        .ok_or_else(|| HarnessError::new(format!("missing value for {key} in {text:?}")))?
        .map_err(|e| HarnessError::new(format!("bad value for {key}: {e}")))?;
    Ok((value, &rest[de.byte_offset()..]))
}

impl fmt::Display for Provenance {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.render())
    }
}

/// A recorded case.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Snapshot {
    /// Case name (file stem).
    pub case: String,
    /// Where the expected values came from.
    pub provenance: Provenance,
    /// How rows are compared.
    pub compare: Compare,
    /// The expected outcome.
    pub outcome: Outcome,
}

const HEADER: &str = "# glaux fidelity snapshot — generated by glaux-fidelity; do not edit by hand";

impl Snapshot {
    /// File name for `case`.
    pub fn file_name(case: &str) -> String {
        format!("{case}.snap")
    }

    /// Render to the text format.
    pub fn render(&self) -> String {
        let mut out = String::new();
        out.push_str(HEADER);
        out.push('\n');
        out.push_str(&format!("# case: {}\n", self.case));
        out.push_str(&format!("# provenance: {}\n", self.provenance.render()));
        out.push_str(&format!("# compare: {}\n", self.compare.as_str()));
        out.push_str(&format!("status: {}\n", self.outcome.status()));
        match &self.outcome {
            Outcome::Succeeded { columns, rows } => {
                let cols: Vec<Value> = columns
                    .iter()
                    .map(|c| Value::Array(vec![c.name.clone().into(), c.type_name.clone().into()]))
                    .collect();
                out.push_str(&format!("columns: {}\n", Value::Array(cols)));
                for row in rows {
                    let cells: Vec<Value> = row
                        .iter()
                        .map(|c| c.clone().map(Value::String).unwrap_or(Value::Null))
                        .collect();
                    out.push_str(&format!("row: {}\n", Value::Array(cells)));
                }
            }
            Outcome::Failed { message } => {
                out.push_str(&format!("error: {}\n", Value::String(message.clone())));
            }
        }
        out
    }

    /// Parse the text format. Every line must be understood; a stray or
    /// malformed line is an error, never ignored.
    pub fn parse(text: &str) -> Result<Self> {
        let bad = |what: String| HarnessError::new(format!("malformed snapshot: {what}"));
        let mut case = None;
        let mut provenance = None;
        let mut compare = None;
        let mut status = None;
        let mut columns: Option<Vec<Column>> = None;
        let mut rows = Vec::new();
        let mut error = None;
        for (i, line) in text.lines().enumerate() {
            let line_no = i + 1;
            if line == HEADER {
                continue;
            }
            if let Some(v) = line.strip_prefix("# case: ") {
                case = Some(v.to_string());
            } else if let Some(v) = line.strip_prefix("# provenance: ") {
                provenance = Some(Provenance::parse(v)?);
            } else if let Some(v) = line.strip_prefix("# compare: ") {
                compare = Some(
                    Compare::parse(v)
                        .ok_or_else(|| bad(format!("line {line_no}: compare {v:?}")))?,
                );
            } else if let Some(v) = line.strip_prefix("status: ") {
                status = Some(v.to_string());
            } else if let Some(v) = line.strip_prefix("columns: ") {
                let parsed: Vec<(String, String)> = serde_json::from_str(v)
                    .map_err(|e| bad(format!("line {line_no}: columns: {e}")))?;
                columns = Some(
                    parsed
                        .into_iter()
                        .map(|(name, type_name)| Column { name, type_name })
                        .collect(),
                );
            } else if let Some(v) = line.strip_prefix("row: ") {
                let cells: Vec<Option<String>> = serde_json::from_str(v)
                    .map_err(|e| bad(format!("line {line_no}: row: {e}")))?;
                rows.push(cells);
            } else if let Some(v) = line.strip_prefix("error: ") {
                let message: String = serde_json::from_str(v)
                    .map_err(|e| bad(format!("line {line_no}: error: {e}")))?;
                error = Some(message);
            } else if line.trim().is_empty() {
                continue;
            } else {
                return Err(bad(format!("line {line_no}: unexpected {line:?}")));
            }
        }
        let case = case.ok_or_else(|| bad("missing `# case:`".into()))?;
        let provenance = provenance.ok_or_else(|| bad("missing `# provenance:`".into()))?;
        let compare = compare.ok_or_else(|| bad("missing `# compare:`".into()))?;
        let outcome = match status.as_deref() {
            Some("SUCCEEDED") => {
                let columns = columns.ok_or_else(|| bad("SUCCEEDED without `columns:`".into()))?;
                for (i, row) in rows.iter().enumerate() {
                    if row.len() != columns.len() {
                        return Err(bad(format!(
                            "row {i} has {} cells for {} columns",
                            row.len(),
                            columns.len()
                        )));
                    }
                }
                Outcome::Succeeded { columns, rows }
            }
            Some("FAILED") => Outcome::Failed {
                message: error.ok_or_else(|| bad("FAILED without `error:`".into()))?,
            },
            Some(other) => return Err(bad(format!("status {other:?}"))),
            None => return Err(bad("missing `status:`".into())),
        };
        Ok(Snapshot {
            case,
            provenance,
            compare,
            outcome,
        })
    }

    /// Write to `dir/<case>.snap`.
    pub fn write(&self, dir: &Path) -> Result<()> {
        fs::create_dir_all(dir)?;
        fs::write(dir.join(Self::file_name(&self.case)), self.render())?;
        Ok(())
    }

    /// Read `dir/<case>.snap`; `Ok(None)` when there is no snapshot.
    pub fn read(dir: &Path, case: &str) -> Result<Option<Self>> {
        let path = dir.join(Self::file_name(case));
        match fs::read_to_string(&path) {
            Ok(text) => {
                let snap = Self::parse(&text)
                    .map_err(|e| HarnessError::new(format!("{}: {e}", path.display())))?;
                if snap.case != case {
                    return Err(HarnessError::new(format!(
                        "{}: names case {:?}",
                        path.display(),
                        snap.case
                    )));
                }
                Ok(Some(snap))
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(e) => Err(HarnessError::new(format!("{}: {e}", path.display()))),
        }
    }
}

// ---------------------------------------------------------------------------
// Normalization + diff
// ---------------------------------------------------------------------------

/// Canonical comparison key of one cell, per column type.
fn canonical(column: &Column, cell: &Option<String>) -> String {
    match cell {
        None => "\u{0}NULL".to_string(),
        Some(text) if column.is_floating() => match parse_float(text) {
            Some(v) if v.is_finite() => format!("{v:.12e}"),
            Some(v) => v.to_string(),
            None => text.clone(),
        },
        Some(text) if column.is_timestamp() => parse_timestamp(text)
            .map(|t| t.format("%Y-%m-%d %H:%M:%S%.9f").to_string())
            .unwrap_or_else(|| text.clone()),
        Some(text) => text.clone(),
    }
}

fn parse_float(text: &str) -> Option<f64> {
    match text {
        "NaN" => Some(f64::NAN),
        "Infinity" => Some(f64::INFINITY),
        "-Infinity" => Some(f64::NEG_INFINITY),
        _ => text.parse().ok(),
    }
}

/// Athena prints `timestamp` as `yyyy-MM-dd HH:mm:ss.SSS`; glaux the same.
/// Accept any fraction length (or none) and the ISO `T` separator so that
/// representation never masquerades as a value difference.
fn parse_timestamp(text: &str) -> Option<NaiveDateTime> {
    let normalized = text.replacen('T', " ", 1);
    NaiveDateTime::parse_from_str(&normalized, "%Y-%m-%d %H:%M:%S%.f")
        .or_else(|_| NaiveDateTime::parse_from_str(&normalized, "%Y-%m-%d %H:%M:%S"))
        .ok()
}

/// Whether two cells of `column` are equal under the normalization rules.
fn cells_equal(column: &Column, expected: &Option<String>, actual: &Option<String>) -> bool {
    match (expected, actual) {
        (None, None) => true,
        (Some(e), Some(a)) => {
            if e == a {
                return true;
            }
            if column.is_floating()
                && let (Some(x), Some(y)) = (parse_float(e), parse_float(a))
            {
                if x.is_nan() || y.is_nan() {
                    return x.is_nan() && y.is_nan();
                }
                if x.is_infinite() || y.is_infinite() {
                    return x == y;
                }
                let scale = x.abs().max(y.abs()).max(1.0);
                return (x - y).abs() <= FLOAT_RELATIVE_TOLERANCE * scale;
            }
            if column.is_timestamp()
                && let (Some(x), Some(y)) = (parse_timestamp(e), parse_timestamp(a))
            {
                return x == y;
            }
            false
        }
        _ => false,
    }
}

fn show(cell: &Option<String>) -> String {
    match cell {
        None => "NULL".to_string(),
        Some(s) => format!("{s:?}"),
    }
}

/// Compare `actual` (glaux) against `expected` (the snapshot). Returns the
/// differences, empty when they agree. `expect_error` is the corpus
/// needle for negative cases: a failure must name it on the glaux side,
/// whatever Athena's own wording was.
pub fn diff(
    expected: &Outcome,
    actual: &Outcome,
    compare: Compare,
    expect_error: Option<&str>,
) -> Vec<String> {
    let mut out = Vec::new();
    match (expected, actual) {
        (Outcome::Failed { message: want }, Outcome::Failed { message: got }) => {
            if let Some(needle) = expect_error
                && !got.contains(needle)
            {
                out.push(format!(
                    "glaux error does not name {needle:?}: {got}\n  (recorded error: {want})"
                ));
            }
        }
        (Outcome::Failed { message }, Outcome::Succeeded { rows, .. }) => out.push(format!(
            "recorded FAILED ({message}) but glaux SUCCEEDED with {} row(s)",
            rows.len()
        )),
        (Outcome::Succeeded { rows, .. }, Outcome::Failed { message }) => out.push(format!(
            "recorded SUCCEEDED with {} row(s) but glaux FAILED: {message}",
            rows.len()
        )),
        (
            Outcome::Succeeded {
                columns: want_cols,
                rows: want_rows,
            },
            Outcome::Succeeded {
                columns: got_cols,
                rows: got_rows,
            },
        ) => {
            if want_cols != got_cols {
                let render = |cols: &[Column]| {
                    cols.iter()
                        .map(|c| format!("{} {}", c.name, c.type_name))
                        .collect::<Vec<_>>()
                        .join(", ")
                };
                out.push(format!(
                    "columns differ:\n  expected: {}\n  actual:   {}",
                    render(want_cols),
                    render(got_cols)
                ));
                return out;
            }
            if want_rows.len() != got_rows.len() {
                out.push(format!(
                    "row count differs: expected {}, actual {}",
                    want_rows.len(),
                    got_rows.len()
                ));
            }
            let (want_rows, got_rows) = match compare {
                Compare::Ordered => (want_rows.clone(), got_rows.clone()),
                Compare::Unordered => (sorted(want_cols, want_rows), sorted(want_cols, got_rows)),
            };
            let mut shown = 0;
            for (i, (want, got)) in want_rows.iter().zip(&got_rows).enumerate() {
                let mismatched: Vec<String> = want_cols
                    .iter()
                    .zip(want.iter().zip(got))
                    .filter(|(c, (w, g))| !cells_equal(c, w, g))
                    .map(|(c, (w, g))| format!("{}: expected {} got {}", c.name, show(w), show(g)))
                    .collect();
                if !mismatched.is_empty() {
                    shown += 1;
                    if shown <= 10 {
                        out.push(format!("row {i}: {}", mismatched.join("; ")));
                    }
                }
            }
            if shown > 10 {
                out.push(format!("... and {} more differing row(s)", shown - 10));
            }
        }
    }
    out
}

fn sorted(columns: &[Column], rows: &[Vec<Option<String>>]) -> Vec<Vec<Option<String>>> {
    let mut keyed: Vec<(Vec<String>, Vec<Option<String>>)> = rows
        .iter()
        .map(|row| {
            (
                columns
                    .iter()
                    .zip(row)
                    .map(|(c, cell)| canonical(c, cell))
                    .collect(),
                row.clone(),
            )
        })
        .collect();
    keyed.sort();
    keyed.into_iter().map(|(_, row)| row).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn col(name: &str, ty: &str) -> Column {
        Column {
            name: name.into(),
            type_name: ty.into(),
        }
    }

    fn rows(cells: &[&[Option<&str>]]) -> Vec<Vec<Option<String>>> {
        cells
            .iter()
            .map(|r| r.iter().map(|c| c.map(str::to_string)).collect())
            .collect()
    }

    #[test]
    fn snapshot_round_trips_through_text() {
        let snap = Snapshot {
            case: "demo".into(),
            provenance: Provenance::Athena {
                region: "eu-central-1".into(),
                engine: "Athena engine version 3".into(),
                recorded: "2026-08-21".into(),
            },
            compare: Compare::Unordered,
            outcome: Outcome::Succeeded {
                columns: vec![col("a", "bigint"), col("b|c", "varchar")],
                rows: rows(&[&[Some("1"), Some("x|y\n\"z\"")], &[None, Some("")]]),
            },
        };
        let text = snap.render();
        assert_eq!(Snapshot::parse(&text).unwrap(), snap);

        let failed = Snapshot {
            case: "neg".into(),
            provenance: Provenance::Unverified {
                recorded: "2026-08-21".into(),
            },
            compare: Compare::Ordered,
            outcome: Outcome::Failed {
                message: "SYNTAX_ERROR: line 1:8".into(),
            },
        };
        assert_eq!(Snapshot::parse(&failed.render()).unwrap(), failed);
        assert!(!failed.provenance.is_verified());
    }

    #[test]
    fn malformed_snapshots_are_errors() {
        let text = "# case: x\n# provenance: UNVERIFIED recorded=2026-08-21\n# compare: ordered\nstatus: SUCCEEDED\ncolumns: [[\"a\",\"bigint\"]]\nrow: [\"1\",\"2\"]\n";
        assert!(
            Snapshot::parse(text)
                .unwrap_err()
                .to_string()
                .contains("2 cells")
        );
        let text = "# case: x\n# provenance: UNVERIFIED recorded=2026-08-21\n# compare: ordered\nstatus: SUCCEEDED\ncolumns: []\nbogus line\n";
        assert!(
            Snapshot::parse(text)
                .unwrap_err()
                .to_string()
                .contains("bogus")
        );
        assert!(Snapshot::parse("").is_err());
    }

    #[test]
    fn floats_compare_within_tolerance_and_specials_exactly() {
        let d = col("d", "double");
        assert!(cells_equal(
            &d,
            &Some("0.1".into()),
            &Some("0.10000000000000001".into())
        ));
        assert!(!cells_equal(
            &d,
            &Some("0.1".into()),
            &Some("0.1001".into())
        ));
        assert!(cells_equal(&d, &Some("NaN".into()), &Some("NaN".into())));
        assert!(!cells_equal(
            &d,
            &Some("Infinity".into()),
            &Some("-Infinity".into())
        ));
        assert!(!cells_equal(&d, &Some("1.0".into()), &None));
        let v = col("v", "varchar");
        assert!(!cells_equal(&v, &Some("0.1".into()), &Some("0.10".into())));
    }

    #[test]
    fn timestamps_compare_as_instants() {
        let t = col("t", "timestamp");
        assert!(cells_equal(
            &t,
            &Some("2024-01-05 10:30:00.000".into()),
            &Some("2024-01-05T10:30:00".into())
        ));
        assert!(!cells_equal(
            &t,
            &Some("2024-01-05 10:30:00.000".into()),
            &Some("2024-01-05 10:30:00.001".into())
        ));
    }

    #[test]
    fn unordered_comparison_ignores_row_order_but_not_multiplicity() {
        let cols = vec![col("a", "bigint"), col("d", "double")];
        let expected = Outcome::Succeeded {
            columns: cols.clone(),
            rows: rows(&[&[Some("1"), Some("1.5")], &[Some("2"), Some("2.5")]]),
        };
        let actual = Outcome::Succeeded {
            columns: cols.clone(),
            rows: rows(&[&[Some("2"), Some("2.5")], &[Some("1"), Some("1.5")]]),
        };
        assert!(diff(&expected, &actual, Compare::Unordered, None).is_empty());
        assert!(!diff(&expected, &actual, Compare::Ordered, None).is_empty());
        let dup = Outcome::Succeeded {
            columns: cols,
            rows: rows(&[&[Some("1"), Some("1.5")], &[Some("1"), Some("1.5")]]),
        };
        assert!(!diff(&expected, &dup, Compare::Unordered, None).is_empty());
    }

    #[test]
    fn status_and_column_type_differences_are_reported() {
        let ok = Outcome::Succeeded {
            columns: vec![col("a", "bigint")],
            rows: rows(&[&[Some("1")]]),
        };
        let other_type = Outcome::Succeeded {
            columns: vec![col("a", "integer")],
            rows: rows(&[&[Some("1")]]),
        };
        assert!(diff(&ok, &other_type, Compare::Ordered, None)[0].contains("columns differ"));
        let failed = Outcome::Failed {
            message: "TYPE_MISMATCH: x".into(),
        };
        assert!(diff(&ok, &failed, Compare::Ordered, None)[0].contains("glaux FAILED"));
        assert!(diff(&failed, &ok, Compare::Ordered, None)[0].contains("glaux SUCCEEDED"));
        // Both failed: glaux must name the corpus needle, Athena's wording is free.
        let glaux_err = Outcome::Failed {
            message: "COLUMN_NOT_FOUND: nope".into(),
        };
        assert!(diff(&failed, &glaux_err, Compare::Ordered, Some("nope")).is_empty());
        assert!(!diff(&failed, &glaux_err, Compare::Ordered, Some("other")).is_empty());
    }
}
